config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	devise_scope :user do
	  get '/users/sign_out' => 'devise/sessions#destroy'
	end

	# scope "(:locale)", locale: /en|fr/ do 
		root to: 'models#index' 
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
		resources :models, only: [:index, :show, :new, :create, :update, :edit]
	# end
	delete 'models/:id', to: 'models#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
	has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
	def index
		@models = Model.all
	end

	def show
	  @model = Model.find(params[:id])
	end


	def new
	  @model = Model.new
	end

	def create
	  @model = Model.new(model_params)
	  if @model.save
	    redirect_to model_path(@model)
	  else
	    render :new
	  end
	end

	def edit
	  @model = Model.find(params[:id])
	end

	def update
	  @model = Model.find(params[:id])
	  @model.update(model_params)
	  redirect_to model_path(@model)
	end

	def destroy
	  @model = Model.find(params[:id])
	  @model.destroy
	  redirect_to models_path
	end

	private

	def model_params
	  params.require(:model).permit(:first_name, :last_name, :description, :age, :gender, :role, :category, :based_in, :height, :chest, :waist, :hips, :foot, :hair, :eye, :email, :instagram, photos: [])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skymgmt</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body data-controller="cursor" style=" <%= 'width: 100vw; overflow-x: hidden;' if params[:action] == 'index'%>">
    <div data-controller="modal">    
      <%= render 'shared/header' %>
      <%= yield %>
      <%= render 'shared/footer' %>
      <% if params[:action] == 'index' %>
        <%= render 'shared/modal' %>
      <% end %>
    </div>
  </body>

  <div class="cursor-dot-outline"></div>
  <div class="cursor-dot"></div>
</html>

app/views/models/edit.html.erb
<div data-controller="preview">
	<%= simple_form_for @model do |f| %>
		
		<div class="form-side form-left">
			<%= link_to model_path(@model) do %>
				<p>annuler</p>
			<% end %>


			<h3>About</h3>
			<%= f.input :first_name, placeholder: 'first name', label:false %>
			<%= f.input :last_name, placeholder: 'last name', label:false %>

			<div class="category-wrapper py-3">

		        <div class="filter-btn category-item" data-children-count="1">
		          <input type="radio" value="new faces" name="model[category]" id="category_new_faces" class="category-selector form-check-input radio_buttons required">
		          <label class="form-check-label collection_radio_buttons" for="category_new_faces">
		            <p>New Faces</p>
		          </label>
		        </div>

		        <div class="filter-btn category-item" data-children-count="1">
		          <input type="radio" value="talents" name="model[category]" id="category_talents" class="category-selector form-check-input radio_buttons required">
		          <label class="form-check-label collection_radio_buttons" for="category_talents">
		            <p>Talents</p>
		          </label>
		        </div>
	    
	  		</div>

			<%= f.input :description, placeholder: 'Description', label:false, as: :text, input_html: {rows: 5} %>

		  	<div class="d-flex py-2">  
		  		<%= f.input :age, placeholder: '21', label: "YO" %>

		  		<div class="category-wrapper">

			        <div class="filter-btn category-item" data-children-count="1">
			          <input type="radio" value="female" name="model[gender]" id="gender_female" class="category-selector form-check-input radio_buttons required">
			          <label class="form-check-label collection_radio_buttons" for="gender_female">
			            <p>Female</p>
			          </label>
			        </div>

			        <div class="filter-btn category-item" data-children-count="1">
			          <input type="radio" value="male" name="model[gender]" id="gender_male" class="category-selector form-check-input radio_buttons required">
			          <label class="form-check-label collection_radio_buttons" for="gender_male">
			            <p>Male</p>
			          </label>
			        </div>
	        
	      		</div>

		  	</div>	

			<%= f.input :role, placeholder: 'role : Model ? Actor ?', label:false %>

			<%= f.input :based_in, placeholder: 'Paris', label:false %>
	  	</div>

	  	<div class="form-side form-right">

			<h3>Mensurations</h3>
			<div class="mesures">
				<%= f.input :height, placeholder: 'height', label: "CM" %>
				<%= f.input :chest, placeholder: 'chest', label: "CM" %>
				<%= f.input :waist, placeholder: 'waist', label: "CM" %>
				<%= f.input :hips, placeholder: 'hips', label: "CM" %>
			</div>
			<div class="carateristics">
				<%= f.input :foot, placeholder: 'foot size', label:false %>
				<%= f.input :hair, placeholder: 'hair color', label:false %>
				<%= f.input :eye, placeholder: 'eye color', label:false %>
			</div>

			<h3>Contact</h3>
			<%= f.input :email, placeholder: 'email', label:false %>
			<%= f.input :instagram, placeholder: 'instagram link', label:false %>

			<h3>Photos</h3>

			<%= f.input :photos, as: :file, input_html: { multiple: true }, label:false %>
			<div class="preview">
				<ul>
					<% @model.photos.each do |photo| %>
						<li> <%= cl_image_tag photo.key, style: "height: 85vh" %> </li>
					<% end %>
				</ul>
			</div>

		  	<%= f.button :submit, value: "valider", class: "validate-model-btn" %>
		</div>

	<% end %>
</div>

app/views/models/index.html.erb
<div class="container">
	<div class="navbar py-2">
		<h2>skymgmt</h2>
		<%#= image_tag "logo.svg", alt: "skymgmt logo", class: "logo"%>
		<div class="menu d-flex">
			<div class="trigger mx-2">

				<p class="menu-btn modal-btn" data-bs-toggle="modal" data-bs-target="#aboutModalCenter" id="about">about</p>
				<p class="menu-btn modal-btn" data-bs-toggle="modal" data-bs-target="#indexModalCenter" id="index">index</p>
			</div>
			<div class="language">
				<p class="menu-btn"><%= link_to 'fr', root_path(locale: :fr) %></p>
				<p class="menu-btn"><%= link_to 'en', root_path(locale: :en) %></p>
			</div>
		</div>
	</div>
	<div class="cards">

		<% @models.each do |model| %>
		    <div class="card">

    	    	<% if user_signed_in? %>
    		    	<%= link_to destroy_path(model), style: "position: absolute; right: 0; z-index: 1000; margin: 10px;", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    		    		<span class="delete hairline"></span>
    		    	<% end %>
    	    	<% end %>

		    	<%= link_to model_path(model) do %>

			    	<div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= cl_image_path model.photos.first.key if model.photos.first != nil %>'); background-position: center; background-size: cover">	

				    	<div class="card-info">

				    		<div class="top py-1">
					    		<div class="info d-flex justify-content-center">
					    			<p class="px-3"><%= model.category %></p>
					    		</div>
				    		</div>
					        <h2> <%= model.first_name%> <%= model.last_name %></h2>
					        <div class="bottom">
						        <div class="info d-flex justify-content-center">
						        	<% if model.height != "" %>
						        		<p class="px-3">H <%= model.height %> cm</p>
						        	<% end %>
						        	<% if model.chest != "" %>
						        		<p class="px-3">C <%= model.chest %> cm</p>
						        	<% end %>
						        	<% if model.waist != "" %>
						        		<p class="px-3">W <%= model.waist %> cm</p>
						        	<% end %>
						        	<% if model.hips != "" %>
						        		<p class="px-3">H <%= model.hips %> cm</p>
						        	<% end %>
						        </div>
						        <div class="info d-flex justify-content-center">
						        	<% if model.foot != "" %>
						        		<p class="px-3">F <%= model.foot %></p>
						        	<% end %>
						        	<% if model.hair != "" %>
						        		<p class="px-3">H <%= model.hair %></p>
						        	<% end %>
						        	<% if model.eye != "" %>
						        		<p class="px-3">E <%= model.eye %></p>
						        	<% end %>
						        </div>	
					        </div>
				        </div>
			        </div>

			    <% end %>

		    </div>
		<% end %>

		<% if user_signed_in? %>
			<div class="card last-card">
					<%= link_to new_model_path do %>
					  <span class="add hairline"></span>
					<% end %>
			</div>
		<% end %>
	</div>

</div>

app/views/models/new.html.erb
<div data-controller="preview">
	<%= simple_form_for @model do |f| %>

		<div class="form-side form-left">
			<%= link_to models_path do %>
				<p>annuler</p>
			<% end %>


			<h3>About</h3>
			<%= f.input :first_name, placeholder: 'first name', label:false %>
			<%= f.input :last_name, placeholder: 'last name', label:false %>

			<div class="category-wrapper py-3">

		        <div class="filter-btn category-item" data-children-count="1">
		          <input type="radio" value="new faces" name="model[category]" id="category_new_faces" class="category-selector form-check-input radio_buttons required">
		          <label class="form-check-label collection_radio_buttons" for="category_new_faces">
		            <p>New Faces</p>
		          </label>
		        </div>

		        <div class="filter-btn category-item" data-children-count="1">
		          <input type="radio" value="talents" name="model[category]" id="category_talents" class="category-selector form-check-input radio_buttons required">
		          <label class="form-check-label collection_radio_buttons" for="category_talents">
		            <p>Talents</p>
		          </label>
		        </div>
	    
	  		</div>

			<%= f.input :description, placeholder: 'Description', label:false, as: :text, input_html: {rows: 5} %>

		  	<div class="d-flex py-2">  
		  		<%= f.input :age, placeholder: '21', label: "YO" %>

		  		<div class="category-wrapper">

			        <div class="filter-btn category-item" data-children-count="1">
			          <input type="radio" value="female" name="model[gender]" id="gender_female" class="category-selector form-check-input radio_buttons required">
			          <label class="form-check-label collection_radio_buttons" for="gender_female">
			            <p>Female</p>
			          </label>
			        </div>

			        <div class="filter-btn category-item" data-children-count="1">
			          <input type="radio" value="male" name="model[gender]" id="gender_male" class="category-selector form-check-input radio_buttons required">
			          <label class="form-check-label collection_radio_buttons" for="gender_male">
			            <p>Male</p>
			          </label>
			        </div>
	        
	      		</div>

		  	</div>	

			<%= f.input :role, placeholder: 'role : Model ? Actor ?', label:false %>

			<%= f.input :based_in, placeholder: 'Paris', label:false %>
	  	</div>

	  	<div class="form-side form-right">

			<h3>Mensurations</h3>
			<div class="mesures">
				<%= f.input :height, placeholder: 'height', label: "CM" %>
				<%= f.input :chest, placeholder: 'chest', label: "CM" %>
				<%= f.input :waist, placeholder: 'waist', label: "CM" %>
				<%= f.input :hips, placeholder: 'hips', label: "CM" %>
			</div>
			<div class="carateristics">
				<%= f.input :foot, placeholder: 'foot size', label:false %>
				<%= f.input :hair, placeholder: 'hair color', label:false %>
				<%= f.input :eye, placeholder: 'eye color', label:false %>
			</div>

			<h3>Contact</h3>
			<%= f.input :email, placeholder: 'email', label:false %>
			<%= f.input :instagram, placeholder: 'instagram link', label:false %>

			<h3>Photos</h3>

			<%= f.input :photos, as: :file, input_html: { multiple: true }, label:false %>
			<div class="preview">
			</div>

		  	<%= f.button :submit, value: "valider", class: "validate-model-btn" %>
		</div>

	<% end %>
</div>

app/views/models/show.html.erb
<div class="container">
	<div class="back">
		<%= link_to models_path, class: "back" do %>
			<span class="close hairline"></span>
		<% end %>
	</div>

	<div class="column-wrapper d-flex align-items-center" style="height: 100vh; position: absolute; top: 0; left: 0;">

		<div class="inline-show">

			<div class="show-text">
				<p class="model-name pl-3"> <%= @model.first_name%> <%= @model.last_name %></p>
				<div class="mt-5">
					<p class="px-3"> <%= @model.description %> </p>
			        <div class="bottom my-4">
				        <div class="info-show d-flex justify-content-left">
				        	<% if @model.height != "" %>
				        		<p class="px-3">H <%= @model.height %> cm</p>
				        	<% end %>
				        	<% if @model.chest != "" %>
				        		<p class="px-3">C <%= @model.chest %> cm</p>
				        	<% end %>
				        	<% if @model.waist != "" %>
				        		<p class="px-3">W <%= @model.waist %> cm</p>
				        	<% end %>
				        	<% if @model.hips != "" %>
				        		<p class="px-3">H <%= @model.hips %> cm</p>
				        	<% end %>
				        </div>
				        <div class="info-show d-flex justify-content-left">
				        	<% if @model.foot != "" %>
				        		<p class="px-3">F <%= @model.foot %></p>
				        	<% end %>
				        	<% if @model.hair != "" %>
				        		<p class="px-3">H <%= @model.hair %></p>
				        	<% end %>
				        	<% if @model.eye != "" %>
				        		<p class="px-3">E <%= @model.eye %></p>
				        	<% end %>
				        </div>	
			        </div>
			     </div>

			     <div class="contact px-3">
			     	<p></p>
			     	<a href = "mailto: <%= @model.email %>" class="login">MAIL</a>
			     	<a href="<%= @model.instagram %>" class= "login ms-3">INSTAGRAM</a>
			     	<% if user_signed_in? %>	     		
				     	<%= link_to "EDIT",  edit_model_path(@model), class: "ms-3" %>
			     	<% end %>
			     </div>
			</div>

			<% @model.photos.each do |photo| %>
			  		<%= cl_image_tag photo.key%>
			<% end %>
			<div> </div>

		</div>

	</div>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<div class="wrapper-foot">
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-foot"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
</div>

app/views/shared/_header.html.erb
<div class="wrapper">
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
	<p class="text-head"> SCOUTING&nbsp;&nbsp;&nbsp;&nbsp;MANAGMENT&nbsp;&nbsp;&nbsp;&nbsp;CONSULTING&nbsp;&nbsp;&nbsp;&nbsp;CASTING&nbsp;&nbsp;&nbsp;&nbsp;</p>
</div>

app/views/shared/_modal.html.erb
<!-- Full screen modal -->

<div class="modal fade" id="aboutModalCenter" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
  	<div class="modal-content modal-content-about">
  		<div class="modal-left">
		  	<p class="py-2"><%= t 'global' %></p>
		  	<p class="py-2">expert in &nbsp; &nbsp; management, consulting, casting, scouting <br> paris, londres, milan, new york</p>
			<p class="py-2">we tell stories diffenrently</p>
			<div class="ext-link py-4">
				<!-- UPDATE MAILER -->
				<a class= "login" href="mailto: contact@skymgmt.fr">CONTACT@SKYMGMT.FR</a>
				<a class= "login" href="https://instagram.com/skymanagementagency?utm_medium=copy_link">@SKYMANAGEMENT</a>
			</div>
			<div class="asset">
				<p class="py-2">MANAGEMENT</p>
				<p class="py-2"><%= t 'management' %></p>
				<p class="py-2">CASTING</p>
				<p class="py-2"><%= t 'casting' %></p>
			</div>
		</div>
		<div class="modal-right">
			<div class="asset">
				<p class="py-2">CONSULTING</p>
				<p class="py-2"><%= t 'consulting' %></p>
				<p class="py-2">SCOUTING</p>
				<p class="py-2"><%= t 'scouting' %></p>
			</div>

			<% if user_signed_in? %>
				<%= link_to "QUIT EDITOR", destroy_user_session_path, class: "login", style: "position: absolute; bottom: 0px; right:0px; " %>
			<% else %>
				<%= link_to "I'M A TEAM MEMBER", new_user_session_path, class: "login", style: "position: absolute; bottom: 20px; right:0px; " %>
			<% end %>
		</div>
	</div>
  </div>
</div>


<div class="modal fade" id="indexModalCenter" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
  	<div class="modal-content">
  		<p class="c0">new faces</p>
	  	<div class="modal-content-index pb-2" style="text-transform: lowercase;">
	  		<p class="c1">new faces</p>
	  		<p class="c2 lowercase">name</p>
	  		<p class="c3 lowercase">gender</p>
	  		<p class="c4 lowercase">age</p>
	  		<p class="c5 lowercase">based in</p>
	  		<p class="c6 lowercase">type</p>
	  	</div>
	  	<div class="mb-5">
		  	<% @models.each do |model| %>
		  		<% if model.category == "new faces" %>
		  			<%= link_to model_path(model), class: "modal-content-index-line py-2" do %>
			  			<p class="c2"> <%= model.first_name%> <%= model.last_name %> 
			  				<span class="c0"> 
			  					(
			  					<%= "F" if model.gender == "female" %> 
			  					<%= "M" if model.gender == "male" %>
			  					|
			  					<%= model.age %>
			  					)
			  				</span>
			  			</p>
			  			<p class="c3"> 
			  				<%= "F" if model.gender == "female" %> 
			  				<%= "M" if model.gender == "male" %>
			  			</p>
			  			<p class="c4"> <%= model.age %></p>
			  			<p class="c5"> <%= model.based_in %> </p>
			  			<p class="c6"> <%= model.role %> </p>
			  			<div class="img-absolute"><%= cl_image_tag model.photos.first.key if model.photos.first != nil %></div>
			  		<% end %>
			  	<% end %>
		  	<% end %>
	  	</div>
	  	<p class="c0">talents</p>
	  	<div class="modal-content-index pb-2">
	  		<p class="c1">talents</p>
	  		<p class="c2 lowercase">name</p>
	  		<p class="c3 lowercase">gender</p>
	  		<p class="c4 lowercase">age</p>
	  		<p class="c5 lowercase">based in</p>
	  		<p class="c6 lowercase">type</p>
		</div>
		<div class="mb-5">
		  	<% @models.each do |model| %>
	  	  		<% if model.category == "talents" %>
	  		  		<%= link_to model_path(model), class: "modal-content-index-line py-2" do %>
	  		  			<p class="c2"> <%= model.first_name%> <%= model.last_name %> 
	  		  				<span class="c0"> 
	  		  					(
	  		  					<%= "F" if model.gender == "female" %> 
	  		  					<%= "M" if model.gender == "male" %>
	  		  					|
	  		  					<%= model.age %>
	  		  					)
	  		  				</span>
	  		  			</p>
	  		  			<p class="c3"> 
			  				<%= "F" if model.gender == "female" %> 
			  				<%= "M" if model.gender == "male" %>
			  			</p>
			  			<p class="c4"> <%= model.age %></p>
			  			<p class="c5"> <%= model.based_in %> </p>
			  			<p class="c6"> <%= model.role %> </p>
			  			<div class="img-absolute"><%= cl_image_tag model.photos.first.key if model.photos.first != nil %></div>
	  		  		<% end %>
		  	  	<% end %>
			<% end %>
		</div>
	</div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>